### ISSUE TITLE
Generate slideshow on the fly

### ISSUE THREAD

**Issue by ocaisa** [E-CAM/training_portal#7]
The images we upload as slides take quite some space (in a 2 hour video I've seen 50MB of images when the video itself is only 120MB). Because of the way the chapters thumbnails (currently) work in video.js we can't lazy load these images, which means a big delay before the video starts to play as the chapter thumbnails are loaded first.

One way to get around this is to generate the slides on the fly from the timestamps using javascript. There is an example of how to do this at https://jsfiddle.net/epistemex/gdp00x2s/

This should give better performance and lower the bandwidth requirements...but may not play nice with the thumbnail chapters.

**Comment by ocaisa** [comment]
Also done here https://stackoverflow.com/questions/13760805/how-to-take-a-snapshot-of-html5-javascript-based-video-player

**Comment by wpoely86** [comment]
Maybe just let Video.js load a dummy image (placeholder) and replace the dummies one at a time in the background while the video plays?

**Comment by ocaisa** [comment]
Side-stepped in #8 , the chapter thumbnails were really too tiny to be very  useful anyway
